export const FETCH_EMPLOYEE='FETCH_EMPLOYEE'
export const FETCH_EMPLOYEE_SUCCESS='FETCH_EMPLOYEE_SUCCESS'
export const FETCH_EMPLOYEE_FAILURE='FETCH_EMPLOYEE_FAILURE'

export const FETCH_EMPLOYEE_BY_ID='FETCH_EMPLOYEE_BY_ID'
export const FETCH_EMPLOYEE_BY_ID_SUCCESS='FETCH_EMPLOYEE_BY_ID_SUCCESS'
export const FETCH_EMPLOYEE_BY_ID_FAILURE='FETCH_EMPLOYEE_BY_ID_FAILURE'

export const INSERT_EMPLOYEE='INSERT_EMPLOYEE'
export const INSERT_EMPLOYEE_SUCCESS='INSERT_EMPLOYEE_SUCCESS'
export const INSERT_EMPLOYEE_FAILURE='INSERT_EMPLOYEE_FAILURE'

export const UPDATE_EMPLOYEE='UPDATE_EMPLOYEE'
export const UPDATE_EMPLOYEE_SUCCESS='UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_FAILURE='UPDATE_EMPLOYEE_FAILURE'

export const DELETE_EMPLOYEE='DELETE_EMPLOYEE'
export const DELETE_EMPLOYEE_SUCCESS='DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_FAILURE='DELETE_EMPLOYEE_FAILURE'